-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 20:33:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdnormativas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdnormativas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdnormativas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bdnormativas` ;

-- -----------------------------------------------------
-- Table `bdnormativas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnormativas`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdnormativas`.`organolegislativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnormativas`.`organolegislativo` (
  `idorganoLegislativo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idorganoLegislativo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdnormativas`.`tipojurisdiccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnormativas`.`tipojurisdiccion` (
  `idtipoJurisdiccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `idOrganoLegislativo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoJurisdiccion`),
  INDEX `idOrganoLegislativo_idx` (`idOrganoLegislativo` ASC) VISIBLE,
  CONSTRAINT `idOrganoLegislativo`
    FOREIGN KEY (`idOrganoLegislativo`)
    REFERENCES `bdnormativas`.`organolegislativo` (`idorganoLegislativo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdnormativas`.`tiponormativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnormativas`.`tiponormativa` (
  `idtipoNormativa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoNormativa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bdnormativas`.`normativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnormativas`.`normativa` (
  `nroRegistro` INT NOT NULL AUTO_INCREMENT,
  `idTipoNormativa` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `descripcion` VARCHAR(5000) NULL DEFAULT NULL,
  `palabrasClaves` VARCHAR(1000) NULL DEFAULT NULL,
  `idTipoJurisdiccion` INT NOT NULL,
  `nroNormativa` INT NULL DEFAULT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`nroRegistro`),
  INDEX `idTipoNormativa_idx` (`idTipoNormativa` ASC) VISIBLE,
  INDEX `idTipoJurisdiccion_idx` (`idTipoJurisdiccion` ASC) VISIBLE,
  INDEX `idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdnormativas`.`categoria` (`idcategoria`),
  CONSTRAINT `idTipoJurisdiccion`
    FOREIGN KEY (`idTipoJurisdiccion`)
    REFERENCES `bdnormativas`.`tipojurisdiccion` (`idtipoJurisdiccion`),
  CONSTRAINT `idTipoNormativa`
    FOREIGN KEY (`idTipoNormativa`)
    REFERENCES `bdnormativas`.`tiponormativa` (`idtipoNormativa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
